version: 2

references:

  ## Cache

  cache_key: &cache_key
    key: cache-{{ checksum "settings.gradle" }}-{{ checksum "./gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ./.gradle
        - ~/.gradle
        - ~/.m2

  ## Docker image configuration

  config: &config
    working_directory: ~/workspace
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xverify:none -Dfile.encoding=UTF8 -Xmx2048m -XX:+UnlockExperimentalVMOptions"

jobs:

  assemble:
    <<: *config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Compile
          command: ./gradlew assemble
      - *save_cache

  test:
    <<: *config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Execute unit tests
          command: ./gradlew test
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests/test
          destination: /test/
      - *save_cache
      - run:
          name: Generate coverage report
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: build/reports/jacoco/test
          destination: /coverage/
      - run:
          name: Upload coverage report to Codacy
          command: ./gradlew uploadCoverageToCodacy
      - run:
          name: Upload coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  check:
    <<: *config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Check code quality
          command: ./gradlew check
      - *save_cache
      - store_artifacts:
          path: build/reports/checkstyle
          destination: /check/
      - store_artifacts:
          path: build/reports/spotbugs
          destination: /check/
      - store_artifacts:
          path: build/reports/dependency-check-report.html
          destination: /check/

  distribute:
    <<: *config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install jq
          command: sudo apt-get install jq
      - run:
          name: Download frontend artifact
          command: wget $(curl https://circleci.com/api/v1.1/project/github/ayltai/hknews-web/latest/artifacts?circle-token=${CIRCLECI_TOKEN} | jq -r '.[0].url')
          working_directory: src/main/resources/public
      - run:
          name: Decompress frontend artifact
          command: unzip web.zip
          working_directory: src/main/resources/public
      - run:
          name: Delete compressed frontend artifact
          command: rm web.zip
          working_directory: src/main/resources/public
      - run:
          name: Generate backend artifact
          command: ./gradlew bootJar
      - *save_cache
      - store_artifacts:
          path: build/libs
          destination: /build/libs

workflows:
  version: 2
  workflow:
    jobs:
      - assemble
      - test:
          requires:
            - assemble
      - check:
          requires:
            - assemble
      - distribute:
          requires:
            - assemble
            - test
            - check
          filters:
            branches:
              only:
                - master
